apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: gateway