apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }} # add this line for static node port on our environment
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fastapi.selectorLabels" . | nindent 4 }}