apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: {{ .Release.Namespace }}
data:
  USERS_SERVICE_URL: {{ .Values.env.USERS_SERVICE_URL }}
  ORDERS_SERVICE_URL: {{ .Values.env.ORDERS_SERVICE_URL }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL }}