variables:
  REGISTRY: $CI_REGISTRY
  GATEWAY_IMAGE: $CI_REGISTRY_IMAGE/gateway
  USERS_IMAGE: $CI_REGISTRY_IMAGE/users
  ORDERS_IMAGE: $CI_REGISTRY_IMAGE/orders
  IP_VM: 3.249.81.214
  NODEPORT_DEV: 30000
  NODEPORT_QA: 30001
  NODEPORT_STAGING: 30002
  NODEPORT_PROD: 30003
  
image:
  name: "python:3.11-alpine"
  entrypoint: ["/bin/sh", "-c"]

stages:
  - test
  - build
  - deploy-dev
  - deploy-qa
  - deploy-staging
  - deploy-prod

# test-gateway:
#   stage: test
#   script:
#     - cd gateway
#     - pip install -r requirements.txt
#     # - flake8 gateway users orders  # Analyse de style avec flake8
#     - python3 -m pytest --capture=no  # Exécution des tests avec Python

test-users:
  stage: test
  script:
    - cd users
    - pip install -r requirements.txt
    - python3 -m unittest discover tests/

# test-orders:
#   stage: test
#   script:
#     - cd orders
#     - pip install -r requirements.txt
#     # - flake8 gateway users orders  # Analyse de style avec flake8
#     - python3 -m pytest --capture=no  # Exécution des tests avec Python

build-gateway:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd gateway
    - docker build -t $GATEWAY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $GATEWAY_IMAGE:$CI_COMMIT_SHORT_SHA

build-users:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd users
    - docker build -t $USERS_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $USERS_IMAGE:$CI_COMMIT_SHORT_SHA

build-orders:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd orders
    - docker build -t $ORDERS_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $ORDERS_IMAGE:$CI_COMMIT_SHORT_SHA

stop-dev:
  stage: deploy-dev
  variables:
    NAMESPACE: dev
  when: manual
  # Don't stop the "review" for master branch or tags,
  # it is only for branches (so PRs (most of the time))
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    action: stop
  script:
    - sudo helm uninstall orders -n $NAMESPACE
    - sudo helm uninstall users -n $NAMESPACE
    - sudo helm uninstall gateway -n $NAMESPACE

stop-qa:
  stage: deploy-qa
  variables:
    NAMESPACE: qa
  when: manual
  # Don't stop the "review" for master branch or tags,
  # it is only for branches (so PRs (most of the time))
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    action: stop
  script:
    - sudo helm uninstall orders -n $NAMESPACE
    - sudo helm uninstall users -n $NAMESPACE
    - sudo helm uninstall gateway -n $NAMESPACE

stop-staging:
  stage: deploy-staging
  variables:
    NAMESPACE: staging
  when: manual
  # Don't stop the "review" for master branch or tags,
  # it is only for branches (so PRs (most of the time))
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    action: stop
  script:
    - sudo helm uninstall orders -n $NAMESPACE
    - sudo helm uninstall users -n $NAMESPACE
    - sudo helm uninstall gateway -n $NAMESPACE

deploy-dev:
  image: docker:latest
  variables:
    NAMESPACE: dev
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    url: http://$IP_VM:$NODEPORT_DEV
    on_stop: stop-dev
  stage: deploy-dev
  services:
    - docker:dind
  script:
    - echo "$KUBE_CONFIG"
    - cat "$KUBE_CONFIG"
    - echo "$NAMESPACE"
    - echo "$CI_BUILD_REF_NAME"
    # - kubectl get nodes  # Vérification de la connectivité au cluster
    - rm -Rf ~/.kube
    - mkdir ~/.kube/
    - ls
    - kubectl config view --raw # Débuggage
    - cat $KUBE_CONFIG > ~/.kube/config
    - kubectl config view --raw # Débuggage
    - cat $KUBE_CONFIG > $KUBECONFIG
    - kubectl config view --raw # Débuggage
    # - kubectl config view --raw >~/.kube/config
    - curl -k https://127.0.0.1:6443
    - chmod 600 /home/gitlab-runner/builds/t3_zZzCth/0/guillaume.gmn/gitlab_devops_exams.tmp/KUBECONFIG
    - cp ./charts/gateway/values.yaml values-gateway.yml
    - cat values-gateway.yml
    - cp ./charts/users/values.yaml values-users.yml
    - cat values-users.yml
    - cp ./charts/orders/values.yaml values-orders.yml
    - cat values-orders.yml
    - helm upgrade --install gateway ./charts/gateway -n $NAMESPACE --values=values-gateway.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_DEV"
    - helm upgrade --install users ./charts/users -n $NAMESPACE --values=values-users.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_DEV"
    - helm upgrade --install orders ./charts/orders -n $NAMESPACE --values=values-orders.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_DEV"
    
deploy-qa:
  image: docker:latest
  variables:
    NAMESPACE: qa
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    url: http://$IP_VM:$NODEPORT_QA
    on_stop: stop-qa
  stage: deploy-qa
  services:
    - docker:dind
  script:
    - rm -Rf ~/.kube
    - mkdir ~/.kube/
    - ls
    - cat $KUBE_CONFIG > ~/.kube/config
    - kubectl config view --raw >~/.kube/config
    - cp qa/values.yaml values-qa.yml
    - cat values-qa.yml
    - helm upgrade --install gateway ./charts/gateway -n $NAMESPACE --values=values-qa.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_QA"
    - helm upgrade --install users ./charts/users -n $NAMESPACE --values=values-qa.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_QA"
    - helm upgrade --install orders ./charts/orders -n $NAMESPACE --values=values-qa.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_QA"

deploy-staging:
  image: docker:latest
  variables:
    NAMESPACE: staging
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    url: http://$IP_VM:$NODEPORT_STAGING
    on_stop: stop-staging
  stage: deploy-staging
  services:
    - docker:dind
  script:
    - rm -Rf ~/.kube
    - mkdir ~/.kube/
    - ls
    - cat $KUBE_CONFIG > ~/.kube/config
    - kubectl config view --raw >~/.kube/config
    - cp staging/values.yaml values-staging.yml
    - cat values-staging.yml
    - helm upgrade --install gateway ./charts/gateway -n $NAMESPACE --values=values-staging.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_STAGING"
    - helm upgrade --install users ./charts/users -n $NAMESPACE --values=values-staging.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_STAGING"
    - helm upgrade --install orders ./charts/orders -n $NAMESPACE --values=values-staging.yml --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_STAGING"

deploy-prod:
  image: docker:latest
  variables:
    NAMESPACE: prod
  environment:
    name: $NAMESPACE-$CI_BUILD_REF_NAME
    url: http://$IP_VM:$NODEPORT_PROD
  stage: deploy-prod
  when: manual
  only:
    - main
  services:
    - docker:dind
  script:
    - rm -Rf ~/.kube
    - mkdir ~/.kube/
    - ls
    - cat $KUBE_CONFIG > ~/.kube/config
    - kubectl config view --raw >~/.kube/config
    - helm upgrade --install gateway ./charts/gateway -n $NAMESPACE --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_PROD"
    - helm upgrade --install users ./charts/users -n $NAMESPACE --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_PROD"
    - helm upgrade --install orders ./charts/orders -n $NAMESPACE --set image.repository="$CI_REGISTRY_IMAGE" --set service.nodeport="$NODEPORT_PROD"

    