replicaCount: 2
image:
  repository: ${CI_REGISTRY_IMAGE}/gateway
  tag: latest
  pullPolicy: Always
  
imagePullSecrets:
  - name: regcred

service:
  type: NodePort
  port: 80

env:
  USERS_SERVICE_URL: http://users-service:8000
  ORDERS_SERVICE_URL: http://orders-service:8000
  LOG_LEVEL: INFO